In [ ]:
import pandas as pd

print("import data successfully")

import data successfully

In [ ]:
df=pd.read_csv("/content/student_performance.csv")
print("student performance data")

student performance data

In [ ]:
df.head()

,student_id,name,age,gender,department,semester,math_score,science_score,english_score,programming_score,attendance_percentage,city,admission_year
0,1001,Aarav Sharma,19,Male,Computer Science,2,85,78,72,91,92,Mumbai,2023
1,1002,Priya Patel,20,Female,Computer Science,2,76,82,88,79,87,Ahmedabad,2023
2,1003,Rohit Verma,19,Male,Electronics,2,65,74,61,55,78,Delhi,2023
3,1004,Sneha Reddy,20,Female,Mechanical,2,70,80,75,48,95,Hyderabad,2023
4,1005,Arjun Nair,19,Male,Computer Science,2,92,88,81,95,90,Kochi,2023

In [ ]:
df.tail()

# df.head() is used to display the first 5 rows of the DataFrame.
# df.tail() is used to display the last 5 rows of the DataFrame.
# These methods are useful for quickly inspecting the data, checking its structure, and ensuring that the data has been loaded correctly without having to print the entire DataFrame.

,student_id,name,age,gender,department,semester,math_score,science_score,english_score,programming_score,attendance_percentage,city,admission_year
25,1026,Rekha Nair,20,Female,Electronics,2,72,77,73,63,82,Kochi,2023
26,1027,Gaurav Shukla,21,Male,Computer Science,2,84,79,75,87,87,Lucknow,2023
27,1028,Sunita Pillai,19,Female,Civil,2,60,65,68,39,73,Thiruvananthapuram,2023
28,1029,Nitin Jain,20,Male,Mechanical,2,75,76,70,50,84,Indore,2023
29,1030,Akanksha Yadav,19,Female,Computer Science,2,91,93,87,94,95,Agra,2023

In [ ]:
print("Shape of Dataset ",df.shape)
print("Number of students rows:",df.shape[0])
print("Number of columns:",df.shape[1])

Shape of Dataset  (30, 13)
Number of students rows: 30
Number of columns: 13

In [ ]:
print("columns in the datasets:")
print(df.columns.tolist())

columns in the datasets:
['student_id', 'name', 'age', 'gender', 'department', 'semester', 'math_score', 'science_score', 'english_score', 'programming_score', 'attendance_percentage', 'city', 'admission_year']

In [ ]:
print("rows in the dataset")
print(df.index.tolist())

rows in the dataset
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]

In [ ]:
print("dataset types of variables")
print(df.dtypes)

dataset types of variables
student_id                int64
name                     object
age                       int64
gender                   object
department               object
semester                  int64
math_score                int64
science_score             int64
english_score             int64
programming_score         int64
attendance_percentage     int64
city                     object
admission_year            int64
dtype: object

In [ ]:
df.describe()

,student_id,age,semester,math_score,science_score,english_score,programming_score,attendance_percentage,admission_year
count,30.000000,30.000000,30.0,30.000000,30.000000,30.000000,30.000000,30.000000,30.0
mean,1015.500000,19.733333,2.0,76.066667,77.833333,74.166667,67.600000,84.500000,2023.0
std,8.803408,0.739680,0.0,11.467896,8.554423,10.003735,21.041175,9.379913,0.0
min,1001.000000,19.000000,2.0,56.000000,61.000000,55.000000,38.000000,65.000000,2023.0
25%,1008.250000,19.000000,2.0,67.250000,71.250000,67.250000,49.250000,77.250000,2023.0
50%,1015.500000,20.000000,2.0,75.500000,78.000000,75.000000,66.000000,86.500000,2023.0
75%,1022.750000,20.000000,2.0,85.750000,83.750000,81.750000,88.750000,91.750000,2023.0
max,1030.000000,21.000000,2.0,95.000000,93.000000,90.000000,97.000000,98.000000,2023.0

In [ ]:
print("missing value in each column:")
print(df.isnull().sum())
print("\n total missing values:",df.isnull().sum().sum())

missing value in each column:
student_id               0
name                     0
age                      0
gender                   0
department               0
semester                 0
math_score               0
science_score            0
english_score            0
programming_score        0
attendance_percentage    0
city                     0
admission_year           0
dtype: int64

 total missing values: 0

In [ ]:
print("student names:")
print(df['name'])

student names:
0       Aarav Sharma
1        Priya Patel
2        Rohit Verma
3        Sneha Reddy
4         Arjun Nair
5        Meera Joshi
6        Kiran Kumar
7        Divya Singh
8       Rahul Mishra
9         Ananya Das
10       Vikram Iyer
11       Pooja Gupta
12        Suresh Rao
13     Kavya Nambiar
14       Ajay Tiwari
15      Ritu Agarwal
16      Manoj Pandey
17    Swati Kulkarni
18    Deepak Chauhan
19      Nisha Kapoor
20     Harish Pillai
21       Tanvi Mehta
22      Sanjay Dubey
23     Preeti Saxena
24         Amit Bose
25        Rekha Nair
26     Gaurav Shukla
27     Sunita Pillai
28        Nitin Jain
29    Akanksha Yadav
Name: name, dtype: object

In [ ]:
#view unique dept
print("departments in the datasets:")
print(df['department'].unique())
#it mainly gives unique values

departments in the datasets:
['Computer Science' 'Electronics' 'Mechanical' 'Civil']

In [ ]:
#to know the count of the departments individuals
print("count of departments:")
print(df['department'].value_counts())

count of departments:
department
Computer Science    13
Electronics          6
Mechanical           6
Civil                5
Name: count, dtype: int64

In [ ]:
#filter the data
cs_students=df[df['department']=='Computer Science']
print(f"number of computer science students:{len(cs_students)}")

number of computer science students:13

In [ ]:
high_attendance=df[df['attendance_percentage']>90]
print(f"students with attendance above 90%: {len(high_attendance)}")
print(high_attendance[['name','department','attendance_percentage']])

students with attendance above 90%: 10
              name        department  attendance_percentage
0     Aarav Sharma  Computer Science                     92
3      Sneha Reddy        Mechanical                     95
7      Divya Singh  Computer Science                     96
9       Ananya Das  Computer Science                     98
13   Kavya Nambiar        Mechanical                     91
15    Ritu Agarwal       Electronics                     93
17  Swati Kulkarni  Computer Science                     94
21     Tanvi Mehta  Computer Science                     97
24       Amit Bose  Computer Science                     91
29  Akanksha Yadav  Computer Science                     95

In [ ]:
#filter the data
cs_students=df[df['department']=='Computer Science']
print(cs_students)

    student_id            name  age  gender        department  semester  \
0         1001    Aarav Sharma   19    Male  Computer Science         2
1         1002     Priya Patel   20  Female  Computer Science         2
4         1005      Arjun Nair   19    Male  Computer Science         2
7         1008     Divya Singh   19  Female  Computer Science         2
9         1010      Ananya Das   19  Female  Computer Science         2
12        1013      Suresh Rao   21    Male  Computer Science         2
14        1015     Ajay Tiwari   19    Male  Computer Science         2
17        1018  Swati Kulkarni   19  Female  Computer Science         2
19        1020    Nisha Kapoor   19  Female  Computer Science         2
21        1022     Tanvi Mehta   19  Female  Computer Science         2
24        1025       Amit Bose   19    Male  Computer Science         2
26        1027   Gaurav Shukla   21    Male  Computer Science         2
29        1030  Akanksha Yadav   19  Female  Computer Science         2

    math_score  science_score  english_score  programming_score  \
0           85             78             72                 91
1           76             82             88                 79
4           92             88             81                 95
7           88             91             84                 93
9           95             89             90                 97
12          83             86             77                 88
14          71             69             64                 76
17          90             87             85                 92
19          79             84             81                 83
21          93             90             88                 96
24          86             82             79                 89
26          84             79             75                 87
29          91             93             87                 94

    attendance_percentage        city  admission_year
0                      92      Mumbai            2023
1                      87   Ahmedabad            2023
4                      90       Kochi            2023
7                      96     Lucknow            2023
9                      98     Kolkata            2023
12                     88      Mysore            2023
14                     75      Bhopal            2023
17                     94      Nagpur            2023
19                     89  Chandigarh            2023
21                     97       Surat            2023
24                     91     Kolkata            2023
26                     87     Lucknow            2023
29                     95        Agra            2023

In [ ]:
df['total_score'] = df['math_score'] + df['science_score'] + df['english_score'] + df['programming_score']

#to get the top student mark
print("Top Student Mark : ")
top_student = df[df['total_score'] == df['total_score'].max()]
print(top_student[['name','department','total_score']])

Top Student Mark :
         name        department  total_score
9  Ananya Das  Computer Science          371

In [ ]:
dept_avg=df.groupby('department')['total_score'].mean().round(2)
print("average total score by department:")
print(dept_avg)

average total score by department:
department
Civil               235.80
Computer Science    340.15
Electronics         277.50
Mechanical          267.33
Name: total_score, dtype: float64

In [ ]:
df_stored=df.sort_values(by='total_score',ascending=False)
print("top 10 studentss based on total score:")
print(df_stored[['name','department','total_score','attendance_percentage']].head(10))

top 10 studentss based on total score:
              name        department  total_score  attendance_percentage
9       Ananya Das  Computer Science          371                     98
21     Tanvi Mehta  Computer Science          367                     97
29  Akanksha Yadav  Computer Science          365                     95
4       Arjun Nair  Computer Science          356                     90
7      Divya Singh  Computer Science          356                     96
17  Swati Kulkarni  Computer Science          354                     94
24       Amit Bose  Computer Science          336                     91
12      Suresh Rao  Computer Science          334                     88
19    Nisha Kapoor  Computer Science          327                     89
0     Aarav Sharma  Computer Science          326                     92

Practice Questions

Try Solving

Question 1 : How many students are from the electronic departments?

Question 2 : What is the average attendance of female students?

Question 3 : Who is the students with the lowest programming score?

Question 4 : How many students scored above 80 in math?

Question 5 : What is the average total_score for students with attendance above 90%

In [ ]:
print("count of departments:")
dept_eletronic=df[df['department']=='Electronics']
print(len(dept_eletronic))

count of departments:
6

In [ ]:
#Question 2 : What is the average attendance of female students?
attendance_avg = df[df['gender'] == 'Female']['attendance_percentage'].mean().round(2)
print("Average attendance of Female Students : ")
print(attendance_avg)

Average attendance of Female Students :
88.53

In [ ]:
MINI PROJECT: Student Data Explorer

Onjective:

Create a student performance explorer using python and pandas to analyze student data and generate a detailed report.

dataset columns:

name,

age,

gender,

department,

math_score,

programming_score,

attdance_performance,

total_score

Task to perform:

display project title print a formatted title with separate lines

dataset overview display: -total number of students -total number of columns -number of unique departments

Department-wise Analysis Display the count of students in each department

Score Analysis Find and display: -Highest math score -Lowest math score -Average math score -Average programming score -Averaye attdance percentage

Gender-wise Analysis Calculate and display average total score grouped by gender.

Top Performers Display the top 5 students based on total_score. show: -student Name -Department -Total Score

Attendance Analysis FInd students whose attdance is below 75% Display: -Name -Department -Attdance Percentage If all students have attdance above 75% print a suitable message.

Concept to use:

pandas, DataFrame, groupby(), value_counts(), mean(), max(), min(), sort_values(), interrows(), Conditional statements, f-strings

In [ ]:
# MINI PROJECT : Student Data Explorer

import pandas as pd

# Student Dataset
data = {
    "name":["Ajay","Keerthana","Manoj","Swetha","Hari","Deepika","Rohit","Anitha"],
    "gender":["Male","Female","Male","Female","Male","Female","Male","Female"],
    "department":["CS","IT","ECE","CS","IT","ECE","CS","IT"],
    "math_score":[88,92,76,85,95,80,83,90],
    "programming_score":[91,94,72,87,96,81,85,93],
    "attendance_percentage":[84,95,70,89,97,73,86,91]
}

In [ ]:
# Create DataFrame
df = pd.DataFrame(data)

In [ ]:

# Calculate total score
df["total_score"] = df["math_score"] + df["programming_score"]

In [ ]:
# 1. Project Title
print("="*40)
print("STUDENT PERFORMANCE EXPLORER")
print("="*40)

========================================
STUDENT PERFORMANCE EXPLORER
========================================

In [ ]:
# 2. Dataset Overview
print("\nDataset Overview")

print("Total students:",len(df))
print("Total columns:",len(df.columns))
print("Unique departments:",df["department"].nunique())

Dataset Overview
Total students: 8
Total columns: 7
Unique departments: 3

In [ ]:

# 3. Department Wise Analysis
print("\nDepartment Analysis")

print(df["department"].value_counts())

Department Analysis
department
CS     3
IT     3
ECE    2
Name: count, dtype: int64

In [ ]:
# 4. Score Analysis
print("\nScore Analysis")

print("Highest math score:",df["math_score"].max())
print("Lowest math score:",df["math_score"].min())
print("Average math score:",df["math_score"].mean())
print("Average programming score:",df["programming_score"].mean())
print("Average attendance:",df["attendance_percentage"].mean())

Score Analysis
Highest math score: 95
Lowest math score: 76
Average math score: 86.125
Average programming score: 87.375
Average attendance: 85.625

In [ ]:
# 5. Gender Wise Analysis
print("\nGender Wise Analysis")

print(df.groupby("gender")["total_score"].mean())

Gender Wise Analysis
gender
Female    175.5
Male      171.5
Name: total_score, dtype: float64

In [ ]:
# 6. Top Performers
print("\nTop 5 Students")

top_students = df.sort_values( by="total_score", ascending=False)
print(top_students[["name","department","total_score"]].head(5))

Top 5 Students
        name department  total_score
4       Hari         IT          191
1  Keerthana         IT          186
7     Anitha         IT          183
0       Ajay         CS          179
3     Swetha         CS          172

In [ ]:
# 7. Attendance Analysis
print("\nAttendance Analysis")

low_attendance = df[
df["attendance_percentage"] < 75
]

if len(low_attendance) > 0:

    print(
    low_attendance[
    ["name",
     "department",
     "attendance_percentage"]
    ]
    )

else:

    print(
    "All students attendance above 75%"
    )

Attendance Analysis
      name department  attendance_percentage
2    Manoj        ECE                     70
5  Deepika        ECE                     73